
services:
  fastapi:
    environment:
      - PYTHONPATH=/app
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  frontend:
    build: ./travelog-frontend
    ports:
      - "80:80"
    depends_on:
      - fastapi

  mongodb:
    image: mongo
    ports:
      - "27018:27017"
